LIST p = 18f4520
    #include<p18f4520.inC>
	CONFIG OSC = INTIO67
	CONFIG WDT = OFF
	org 0x00
Initial:
    
start:
    CLRF WREG
    LFSR 0,0x100
    MOVLW 0xB5
    MOVWF POSTINC0, 0
    MOVLW 0xF3
    MOVWF POSTINC0, 0
    MOVLW 0x64
    MOVWF POSTINC0, 0
    MOVLW 0x7F
    MOVWF POSTINC0, 0
    MOVLW 0x98
    MOVWF POSTINC0, 0
    
    CLRF TRISB
    CLRF TRISC
    CLRF TRISD
    MOVLW 0x04
    ADDWF TRISC, 1
    MOVLW 0x05
    ADDWF TRISD, 1
    
    LFSR 0,0x100
loop1:
    CLRF WREG
    MOVFF INDF0, WREG
    LFSR 1,0x101
    MOVFF INDF1, TRISB
    loop2:
	CPFSLT TRISB
	GOTO NEXT
	MOVFF INDF0, WREG
	MOVFF INDF1, INDF0
	MOVFF WREG, INDF1
	NEXT:
	    MOVFF POSTINC1, TRISB
	    DECFSZ TRISC
	    GOTO loop2
	CLRF WREG
	MOVLW 0x05
	MOVWF TRISC
	NOP POSTINC0
    DECFSZ TRISD
    GOTO loop1
end


